repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2  # Update to the latest version
    hooks:
      - id: poetry-check  # Ensures pyproject.toml is valid

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1  # Update to the latest version
    hooks:
      - id: ruff
      - id: ruff-format
